import { ProgramEnrollment } from '..';

export const patientUUID = '02f47490-d657-48ee-98e7-4c9133ea168b';
export const mockEnrollments: ProgramEnrollment[] = [
  {
    uuid: 'enrollment-1',
    display: 'HIV Program',
    patient: {
      uuid: patientUUID,
      display: 'John Doe',
      identifiers: [
        {
          uuid: 'identifier-1',
          display: 'BAH123456',
          links: [],
        },
      ],
      person: {
        uuid: 'person-1',
        display: 'John Doe',
        gender: 'M',
        age: 35,
        birthdate: '1988-01-01',
        birthdateEstimated: false,
        dead: false,
        deathDate: null,
        causeOfDeath: null,
        preferredName: {
          uuid: 'name-1',
          display: 'John Doe',
        },
        preferredAddress: null,
        attributes: [],
        voided: false,
        birthtime: null,
        deathdateEstimated: false,
        links: [],
        resourceVersion: '1.0',
      },
      voided: false,
      links: [],
      resourceVersion: '1.0',
    },
    program: {
      uuid: 'program-1',
      name: 'HIV Program',
      display: 'HIV Program',
      retired: false,
      concept: {
        uuid: 'concept-1',
        display: 'HIV Program Concept',
        links: [],
        resourceVersion: '1.0',
      },
      allWorkflows: [],
      links: [],
      resourceVersion: '1.0',
    },
    dateEnrolled: '2023-01-01',
    dateCompleted: null,
    location: null,
    voided: false,
    outcome: null,
    states: [],
    attributes: [
      {
        display: 'ID_Number: 123145',
        uuid: '88370695-3803-49fb-89bf-97fd871210b2',
        attributeType: {
          uuid: '435e6fa9-45af-428b-a7e5-cef7c1929928',
          display: 'ID_Number',
          description: 'ID Number',
          retired: false,
          links: [
            {
              rel: 'self',
              uri: 'http://localhost/openmrs/ws/rest/v1/programattributetype/435e6fa9-45af-428b-a7e5-cef7c1929928',
              resourceAlias: 'programattributetype',
            },
          ],
        },
        value: '123145',
        voided: false,
        links: [
          {
            rel: 'self',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/88370695-3803-49fb-89bf-97fd871210b2',
            resourceAlias: 'attribute',
          },
          {
            rel: 'full',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/88370695-3803-49fb-89bf-97fd871210b2?v=full',
            resourceAlias: 'attribute',
          },
        ],
        resourceVersion: '1.9',
      },
      {
        display: 'Treatment Date: Wed Feb 04 00:00:00 UTC 2026',
        uuid: '3d255887-35e4-4f05-82c5-ba8407cd234c',
        attributeType: {
          uuid: 'ac3a1304-e290-4017-bb0a-8179263eb7b5',
          display: 'Treatment Date',
          description: 'Treatment Date',
          retired: false,
          links: [
            {
              rel: 'self',
              uri: 'http://localhost/openmrs/ws/rest/v1/programattributetype/ac3a1304-e290-4017-bb0a-8179263eb7b5',
              resourceAlias: 'programattributetype',
            },
          ],
        },
        value: '2026-02-04T00:00:00.000+0000',
        voided: false,
        links: [
          {
            rel: 'self',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/3d255887-35e4-4f05-82c5-ba8407cd234c',
            resourceAlias: 'attribute',
          },
          {
            rel: 'full',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/3d255887-35e4-4f05-82c5-ba8407cd234c?v=full',
            resourceAlias: 'attribute',
          },
        ],
        resourceVersion: '1.9',
      },
      {
        display: 'Patient Stage: Concept #57452',
        uuid: '67237ec0-d604-4a36-bfdb-b3dfa90b88d6',
        attributeType: {
          uuid: '13bedad6-104b-40bf-bc6a-b1905c3e7750',
          display: 'Patient Stage',
          description: 'Patient Stage',
          retired: false,
          links: [
            {
              rel: 'self',
              uri: 'http://localhost/openmrs/ws/rest/v1/programattributetype/13bedad6-104b-40bf-bc6a-b1905c3e7750',
              resourceAlias: 'programattributetype',
            },
          ],
        },
        value: {
          uuid: 'b5a4b35a-bcf7-4245-93b3-b4291d029508',
          display: 'Initial Stage',
          name: {
            display: 'Initial Stage',
            uuid: '24a33f93-acbb-3ce5-9aba-0398a8b8ef8d',
            name: 'Initial Stage',
            locale: 'en',
            localePreferred: true,
            conceptNameType: 'FULLY_SPECIFIED',
            links: [
              {
                rel: 'self',
                uri: 'http://localhost/openmrs/ws/rest/v1/concept/b5a4b35a-bcf7-4245-93b3-b4291d029508/name/24a33f93-acbb-3ce5-9aba-0398a8b8ef8d',
                resourceAlias: 'name',
              },
              {
                rel: 'full',
                uri: 'http://localhost/openmrs/ws/rest/v1/concept/b5a4b35a-bcf7-4245-93b3-b4291d029508/name/24a33f93-acbb-3ce5-9aba-0398a8b8ef8d?v=full',
                resourceAlias: 'name',
              },
            ],
            resourceVersion: '1.9',
          },
          descriptions: [],
          mappings: [],
          answers: [],
          setMembers: [],
          attributes: [],
          links: [
            {
              rel: 'self',
              uri: 'http://localhost/openmrs/ws/rest/v1/concept/b5a4b35a-bcf7-4245-93b3-b4291d029508',
              resourceAlias: 'concept',
            },
            {
              rel: 'full',
              uri: 'http://localhost/openmrs/ws/rest/v1/concept/b5a4b35a-bcf7-4245-93b3-b4291d029508?v=full',
              resourceAlias: 'concept',
            },
          ],
          resourceVersion: '2.0',
        },
        voided: false,
        links: [
          {
            rel: 'self',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/67237ec0-d604-4a36-bfdb-b3dfa90b88d6',
            resourceAlias: 'attribute',
          },
          {
            rel: 'full',
            uri: 'http://localhost/openmrs/ws/rest/v1/programenrollment/c6347b2d-3519-4e12-972f-face180e2645/attribute/67237ec0-d604-4a36-bfdb-b3dfa90b88d6?v=full',
            resourceAlias: 'attribute',
          },
        ],
        resourceVersion: '1.9',
      },
    ],
    episodeUuid: 'episode-1',
    auditInfo: {
      creator: {
        uuid: 'user-1',
        display: 'Admin User',
        links: [],
      },
      dateCreated: '2023-01-01T10:00:00.000+0000',
      changedBy: null,
      dateChanged: null,
    },
    links: [],
    resourceVersion: '1.0',
  },
  {
    uuid: 'enrollment-2',
    display: 'TB Program - Active',
    patient: {
      uuid: patientUUID,
      display: 'John Doe',
      identifiers: [
        {
          uuid: 'identifier-1',
          display: 'BAH123456',
          links: [],
        },
      ],
      person: {
        uuid: 'person-1',
        display: 'John Doe',
        gender: 'M',
        age: 35,
        birthdate: '1988-01-01',
        birthdateEstimated: false,
        dead: false,
        deathDate: null,
        causeOfDeath: null,
        preferredName: {
          uuid: 'name-1',
          display: 'John Doe',
        },
        preferredAddress: null,
        attributes: [],
        voided: false,
        birthtime: null,
        deathdateEstimated: false,
        links: [],
        resourceVersion: '1.0',
      },
      voided: false,
      links: [],
      resourceVersion: '1.0',
    },
    program: {
      uuid: 'program-2',
      name: 'TB Program',
      display: 'TB Program',
      retired: false,
      concept: {
        uuid: 'concept-2',
        display: 'TB Program Concept',
        links: [],
        resourceVersion: '1.0',
      },
      allWorkflows: [],
      links: [],
      resourceVersion: '1.0',
    },
    dateEnrolled: '2024-01-01',
    dateCompleted: null,
    location: null,
    voided: false,
    outcome: null,
    states: [
      {
        uuid: 'state-1',
        startDate: '2024-01-01',
        endDate: '2024-06-01',
        voided: false,
        state: {
          uuid: 'workflow-state-1',
          display: 'Initial Treatment',
          description: 'Initial treatment phase',
          retired: false,
          concept: {
            uuid: 'concept-state-1',
            display: 'Initial Treatment',
            links: [],
            resourceVersion: '1.0',
          },
          links: [],
          resourceVersion: '1.0',
        },
      },
      {
        uuid: 'state-2',
        startDate: '2024-06-01',
        endDate: null,
        voided: false,
        state: {
          uuid: 'workflow-state-2',
          display: 'Continuation Phase',
          description: 'Continuation treatment phase',
          retired: false,
          concept: {
            uuid: 'concept-state-2',
            display: 'Continuation Phase',
            links: [],
            resourceVersion: '1.0',
          },
          links: [],
          resourceVersion: '1.0',
        },
      },
    ],
    attributes: [],
    episodeUuid: 'episode-2',
    auditInfo: {
      creator: {
        uuid: 'user-1',
        display: 'Admin User',
        links: [],
      },
      dateCreated: '2024-01-01T10:00:00.000+0000',
      changedBy: null,
      dateChanged: null,
    },
    links: [],
    resourceVersion: '1.0',
  },
  {
    uuid: 'enrollment-3',
    display: 'Cancer Program - Completed',
    patient: {
      uuid: patientUUID,
      display: 'John Doe',
      identifiers: [
        {
          uuid: 'identifier-1',
          display: 'BAH123456',
          links: [],
        },
      ],
      person: {
        uuid: 'person-1',
        display: 'John Doe',
        gender: 'M',
        age: 35,
        birthdate: '1988-01-01',
        birthdateEstimated: false,
        dead: false,
        deathDate: null,
        causeOfDeath: null,
        preferredName: {
          uuid: 'name-1',
          display: 'John Doe',
        },
        preferredAddress: null,
        attributes: [],
        voided: false,
        birthtime: null,
        deathdateEstimated: false,
        links: [],
        resourceVersion: '1.0',
      },
      voided: false,
      links: [],
      resourceVersion: '1.0',
    },
    program: {
      uuid: 'program-3',
      name: 'Cancer Program',
      display: 'Cancer Program',
      retired: false,
      concept: {
        uuid: 'concept-3',
        display: 'Cancer Program Concept',
        links: [],
        resourceVersion: '1.0',
      },
      allWorkflows: [],
      links: [],
      resourceVersion: '1.0',
    },
    dateEnrolled: '2023-01-01',
    dateCompleted: '2024-12-31',
    location: null,
    voided: false,
    outcome: null,
    states: [
      {
        uuid: 'state-3',
        startDate: '2023-01-01',
        endDate: '2023-06-01',
        voided: false,
        state: {
          uuid: 'workflow-state-3',
          display: 'Diagnosis',
          description: 'Diagnosis phase',
          retired: false,
          concept: {
            uuid: 'concept-state-3',
            display: 'Diagnosis',
            links: [],
            resourceVersion: '1.0',
          },
          links: [],
          resourceVersion: '1.0',
        },
      },
      {
        uuid: 'state-4',
        startDate: '2023-06-01',
        endDate: '2024-01-01',
        voided: false,
        state: {
          uuid: 'workflow-state-4',
          display: 'Active Treatment',
          description: 'Active treatment phase',
          retired: false,
          concept: {
            uuid: 'concept-state-4',
            display: 'Active Treatment',
            links: [],
            resourceVersion: '1.0',
          },
          links: [],
          resourceVersion: '1.0',
        },
      },
      {
        uuid: 'state-5',
        startDate: '2024-01-01',
        endDate: '2024-12-31',
        voided: false,
        state: {
          uuid: 'workflow-state-5',
          display: 'Recovery',
          description: 'Recovery phase',
          retired: false,
          concept: {
            uuid: 'concept-state-5',
            display: 'Recovery',
            links: [],
            resourceVersion: '1.0',
          },
          links: [],
          resourceVersion: '1.0',
        },
      },
    ],
    attributes: [],
    episodeUuid: 'episode-3',
    auditInfo: {
      creator: {
        uuid: 'user-1',
        display: 'Admin User',
        links: [],
      },
      dateCreated: '2023-01-01T10:00:00.000+0000',
      changedBy: null,
      dateChanged: null,
    },
    links: [],
    resourceVersion: '1.0',
  },
];
