import { OPENMRS_REST_V1 } from '../constants/app';

// Module labels
export const MODULE_LABELS = {
  CLINICAL: 'MODULE_LABEL_CLINICAL_KEY',
  REGISTRATION: 'MODULE_LABEL_REGISTRATION_KEY',
} as const;

// Audit log event details mapping
export const AUDIT_LOG_EVENT_DETAILS = {
  VIEWED_CLINICAL_DASHBOARD: {
    eventType: 'VIEWED_CLINICAL_DASHBOARD',
    message: 'VIEWED_CLINICAL_DASHBOARD_MESSAGE',
  },
  EDIT_ENCOUNTER: {
    eventType: 'EDIT_ENCOUNTER',
    message: 'EDIT_ENCOUNTER_MESSAGE',
  },
  VIEWED_REGISTRATION_PATIENT_SEARCH: {
    eventType: 'VIEWED_REGISTRATION_PATIENT_SEARCH',
    message: 'VIEWED_REGISTRATION_PATIENT_SEARCH_MESSAGE',
    module: MODULE_LABELS.REGISTRATION,
  },
  REGISTER_NEW_PATIENT: {
    eventType: 'REGISTER_NEW_PATIENT',
    message: 'REGISTER_NEW_PATIENT_MESSAGE',
    module: MODULE_LABELS.REGISTRATION,
  },
  VIEWED_NEW_PATIENT_PAGE: {
    eventType: 'VIEWED_NEW_PATIENT_PAGE',
    message: 'VIEWED_NEW_PATIENT_PAGE_MESSAGE',
    module: MODULE_LABELS.REGISTRATION,
  },
  OPEN_VISIT: {
    eventType: 'OPEN_VISIT',
    message: 'OPEN_VISIT_MESSAGE',
    module: MODULE_LABELS.REGISTRATION,
  },
  EDIT_PATIENT_DETAILS: {
    eventType: 'EDIT_PATIENT_DETAILS',
    message: 'EDIT_PATIENT_DETAILS_MESSAGE',
    module: MODULE_LABELS.REGISTRATION,
  },
  VIEWED_RADIOLOGY_RESULTS: {
    eventType: 'VIEWED_RADIOLOGY_RESULTS',
    message: 'VIEWED_RADIOLOGY_RESULTS_MESSAGE',
  },
};

export const AUDIT_LOG_URL = OPENMRS_REST_V1 + '/auditlog';
export const AUDIT_LOG_ERROR_MESSAGES = {
  UNKNOWN_EVENT_TYPE: 'AUDIT_LOG_ERROR_UNKNOWN_EVENT_TYPE',
};
